name: Release APK

on:
  pull_request:
    branches:
      - main
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
          
      - name: Build APK
        working-directory: ./BibBuddy
        run: bash ./gradlew assembleDebug --stacktrace
        
        # Upload the APK as a build artifact that can be used by subsequent workflow steps
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.2
        with:
          name: apk
          path: ./BibBuddy/app/build/outputs/apk/debug/app-debug.apk
        
       # Download a build artifact that was previously uploaded in the workflow by the upload-artifact action
      - name: Download APK from build
        uses: actions/download-artifact@v2.0.8
        with:
          name: apk
      
      # Create a release for a tag in the repository  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: This is a release of the created APK
        
      # Upload the apk for the release  
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-debug.apk
          asset_name: BibBuddy.apk
          asset_content_type: application/zip
